### ISSUE TITLE
Deployment of the ingress resource fails - spec.rules[0].http.paths[0].path: Invalid value: "": must be an absolute path

### ISSUE THREAD

**Issue by aureamunoz** [quarkus-for-spring-developers/examples#85]
## Issue

With Quarkus `2.0.0.CR3 or 2.0.0.Final`, the Ingress resource is not correctly generated and we get the following error when we run the ` kubectl apply -f ./target/kubernetes/kubernetes.yml -n quarkus-demo` command

```shell
kubectl apply -f ./target/kubernetes/kubernetes.yml -n quarkus-demo
service/chapter-6-quarkus-rest created
deployment.apps/chapter-6-quarkus-rest created
The Ingress "chapter-6-quarkus-rest" is invalid: 
* spec.rules[0].http.paths[0].path: Invalid value: "": must be an absolute path
* spec.rules[0].http.paths[1].pathType: Required value: pathType must be specified
```

Here after, the generated `kubernetes.yml` file:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ...
  labels:
    ...
  name: chapter-6-quarkus-rest
spec:
  rules:
    - host: chapter-6-quarkus-rest.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              service:
                name: chapter-6-quarkus-rest
                port:
                  name: http
            pathType: Prefix
          - backend:
              service:
                name: chapter-6-quarkus-rest
                port:
                  name: http
```
Had you seen this problem @cmoulliard ? Should we investigate it from the quarkus side?
